-- =========================================================
-- BANCO DE DADOS DO PAINEL DA MARIA CLARA
--
-- ONDE COLAR:
--   1. Entre em https://supabase.com/dashboard e abra o seu projeto.
--   2. No menu da esquerda, clique em "SQL Editor".
--   3. Clique em "New query" (nova consulta).
--   4. Cole TODO este arquivo, do começo ao fim.
--   5. Clique em "Run" (ou aperte Ctrl+Enter / Cmd+Enter).
--   6. Tem que aparecer "Success. No rows returned".
--
-- Pode rodar mais de uma vez sem medo: nada é apagado e as
-- linhas de exemplo só entram quando a tabela está vazia.
-- =========================================================


-- ---------------------------------------------------------
-- 1. QUEM É A DONA
-- Uma pequena "pergunta" que o banco faz a cada leitura ou gravação:
-- "a pessoa logada agora é a Maria Clara, com o e-mail confirmado?"
-- Fica numa área separada (privado), que o site não enxerga.
-- ---------------------------------------------------------
create schema if not exists privado;

create or replace function privado.sou_eu()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from auth.users
    where id = auth.uid()
      and lower(email) = 'mariaugclara@gmail.com'
      and email_confirmed_at is not null
  );
$$;

revoke all on function privado.sou_eu() from public;
grant usage on schema privado to anon, authenticated;
grant execute on function privado.sou_eu() to anon, authenticated;


-- ---------------------------------------------------------
-- 2. AS TABELAS
-- Cada uma tem "id" (número automático) e "criado_em" (data automática).
-- A coluna "exemplo" marca a linha de exemplo, pra você reconhecer e apagar.
-- ---------------------------------------------------------

-- 2.1 VÍDEOS: os trabalhos que aparecem no portfólio
create table if not exists public.videos (
  id         bigint generated by default as identity primary key,
  criado_em  timestamptz not null default now(),
  titulo     text    not null default '',
  link       text    not null default '',
  nicho      text    not null default '',
  formato    text    not null default '',
  marca      text    not null default '',
  destaque   text    not null default '',       -- ex: "2,4M views"
  ordem      integer not null default 0,        -- posição no site (menor aparece antes)
  visivel    boolean not null default true,     -- o olhinho do painel
  exemplo    boolean not null default false
);

-- 2.2 MARCAS: a sua base de contatos de empresa
create table if not exists public.marcas (
  id              bigint generated by default as identity primary key,
  criado_em       timestamptz not null default now(),
  nome            text not null default '',
  instagram       text not null default '',
  email           text not null default '',
  telefone        text not null default '',
  situacao        text not null default 'Lead'
                  check (situacao in ('Lead', 'Conversando', 'Cliente', 'Parada')),
  obs             text not null default '',
  ultimo_contato  date,
  origem          text not null default 'painel',   -- "site" quando veio do formulário
  nicho           text not null default '',         -- Moda, Casa e decoração, Tech...
  exemplo         boolean not null default false
);
-- Para quem já tinha criado a tabela antes: acrescenta o campo nicho
alter table public.marcas add column if not exists nicho text not null default '';

-- 2.3 CALENDÁRIO: o que você vai gravar, editar e postar
create table if not exists public.calendario (
  id         bigint generated by default as identity primary key,
  criado_em  timestamptz not null default now(),
  titulo     text not null default '',
  marca      text not null default '',
  tipo       text not null default 'gravar'  check (tipo in ('gravar', 'editar', 'postar')),
  data       date not null default current_date,
  status     text not null default 'a fazer' check (status in ('a fazer', 'feito')),
  exemplo    boolean not null default false
);

-- 2.4 CAMPANHAS: os trabalhos fechados com as marcas
create table if not exists public.campanhas (
  id         bigint generated by default as identity primary key,
  criado_em  timestamptz not null default now(),
  campanha   text not null default '',
  cliente    text not null default '',
  tipo       text not null default 'Conteúdo'
             check (tipo in ('Conteúdo', 'Publicidade')),
  status     text not null default 'Briefing'
             check (status in ('Briefing', 'Roteiro', 'Aprovação Roteiro', 'Gravação', 'Edição', 'Aprovado', 'Entregue')),
  qtd        integer       not null default 1 check (qtd >= 0),     -- quantos vídeos
  valor      numeric(12,2) not null default 0 check (valor >= 0),   -- valor total da campanha
  prazo      date,
  pagamento  text    not null default 'pendente' check (pagamento in ('pendente', 'pago')),
  ativa      boolean not null default true,
  favorita   boolean not null default false,
  exemplo    boolean not null default false
);

-- 2.5 MARCADOS: o que você já marcou no checklist
-- Cada item marcado vira uma linha com uma chave de texto (ex: "checklist:capa:0").
-- Desmarcou, a linha some.
create table if not exists public.marcados (
  chave       text primary key,
  marcado_em  timestamptz not null default now()
);

-- 2.6 VISITAS: cada visita ao portfólio, para as métricas do painel
-- Não guarda nome, IP, cookie nem nada que identifique a pessoa.
create table if not exists public.visitas (
  id      bigint generated by default as identity primary key,
  data    timestamptz not null default now(),
  pagina  text not null default '/',
  origem  text not null default 'Direto'   -- Instagram, Google, WhatsApp, Direto...
);
create index if not exists visitas_data_idx on public.visitas (data);


-- ---------------------------------------------------------
-- 3. A TRANCA (RLS, Row Level Security)
-- Ligada em TODAS as tabelas. Com ela ligada, o banco nega tudo,
-- a não ser o que as regras (policies) abaixo liberam.
-- ---------------------------------------------------------
alter table public.videos      enable row level security;
alter table public.marcas      enable row level security;
alter table public.calendario  enable row level security;
alter table public.campanhas   enable row level security;
alter table public.marcados    enable row level security;
alter table public.visitas     enable row level security;


-- ---------------------------------------------------------
-- 4. QUEM PODE FAZER O QUÊ (permissões de base)
-- Primeiro tira tudo de quem não está logado ("anon"),
-- depois devolve só o mínimo necessário. É uma segunda tranca,
-- além das regras do bloco 5.
-- ---------------------------------------------------------
revoke all on public.videos, public.marcas, public.calendario,
              public.campanhas, public.marcados, public.visitas
  from anon;

grant select, insert, update, delete
  on public.videos, public.marcas, public.calendario,
     public.campanhas, public.marcados, public.visitas
  to authenticated;

grant select on public.videos  to anon;   -- o site mostra os vídeos (só os visíveis, ver 5.2)
grant insert on public.marcas  to anon;   -- o formulário de contato cria um lead
grant insert on public.visitas to anon;   -- o site registra a visita


-- ---------------------------------------------------------
-- 5. AS REGRAS (policies)
-- "drop policy if exists" apaga a regra antiga antes de criar de novo,
-- pra você poder rodar este arquivo quantas vezes quiser.
-- ---------------------------------------------------------

-- 5.1 A DONA pode ler, criar, editar e apagar TUDO, em todas as tabelas.
drop policy if exists "dona faz tudo" on public.videos;
create policy "dona faz tudo" on public.videos
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.marcas;
create policy "dona faz tudo" on public.marcas
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.calendario;
create policy "dona faz tudo" on public.calendario
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.campanhas;
create policy "dona faz tudo" on public.campanhas
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.marcados;
create policy "dona faz tudo" on public.marcados
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.visitas;
create policy "dona faz tudo" on public.visitas
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

-- 5.2 O SITE pode LER os vídeos, mas só os que estão com o olhinho aberto
-- e que não são a linha de exemplo. É o que faz o portfólio mostrar
-- os vídeos do painel. Os escondidos continuam só seus.
drop policy if exists "site le videos visiveis" on public.videos;
create policy "site le videos visiveis" on public.videos
  for select to anon, authenticated
  using (visivel = true and exemplo = false);

-- 5.3 EXCEÇÃO 1: qualquer pessoa pode INSERIR em marcas, mas só como
-- um lead vindo do formulário do site, e com tamanho de texto limitado.
-- Ela não consegue ler, editar nem apagar nada.
drop policy if exists "formulario do site cria lead" on public.marcas;
create policy "formulario do site cria lead" on public.marcas
  for insert to anon, authenticated
  with check (
        situacao = 'Lead'
    and origem   = 'site'
    and exemplo  = false
    and (ultimo_contato is null or ultimo_contato between current_date - 1 and current_date + 1)
  );

-- 5.4 EXCEÇÃO 2: qualquer pessoa pode INSERIR uma visita, só com a data
-- de agora (ninguém consegue criar visita no passado ou no futuro).
drop policy if exists "site registra visita" on public.visitas;
create policy "site registra visita" on public.visitas
  for insert to anon, authenticated
  with check (
        data between now() - interval '5 minutes' and now() + interval '5 minutes'
    and char_length(pagina) <= 300
    and char_length(origem) <= 60
  );


-- ---------------------------------------------------------
-- 6. LIMITES DE TAMANHO
-- Evita que alguém mande um texto gigante pelo formulário.
-- ---------------------------------------------------------
alter table public.marcas drop constraint if exists marcas_tamanhos;
alter table public.marcas add constraint marcas_tamanhos check (
      char_length(nome)      <= 200
  and char_length(instagram) <= 200
  and char_length(email)     <= 200
  and char_length(telefone)  <= 50
  and char_length(obs)       <= 5000
  and char_length(nicho)     <= 100
);


-- ---------------------------------------------------------
-- 7. UMA LINHA DE EXEMPLO EM CADA LISTA
-- Só entra se a tabela estiver vazia. Todas vêm com exemplo = true,
-- ficam marcadas no painel e não contam nas métricas. Pode apagar.
-- ---------------------------------------------------------
insert into public.videos (titulo, link, nicho, formato, marca, destaque, ordem, visivel, exemplo)
select 'Exemplo: vídeo de skincare', '', 'Selfcare', 'Depoimento', 'Marca Exemplo', '2,4M views', 1, false, true
where not exists (select 1 from public.videos);

insert into public.marcas (nome, instagram, email, telefone, situacao, obs, ultimo_contato, exemplo)
select 'Marca Exemplo', '@marcaexemplo', 'contato@marcaexemplo.com', '', 'Lead',
       'Linha de exemplo, só pra mostrar o formato. Pode apagar.', null, true
where not exists (select 1 from public.marcas);

insert into public.calendario (titulo, marca, tipo, data, status, exemplo)
select 'Exemplo: gravar vídeo de unboxing', 'Marca Exemplo', 'gravar', current_date + 2, 'a fazer', true
where not exists (select 1 from public.calendario);

insert into public.campanhas (campanha, cliente, tipo, status, qtd, valor, prazo, pagamento, ativa, favorita, exemplo)
select 'Campanha Exemplo', 'Marca Exemplo', 'Conteúdo', 'Briefing', 1, 0, current_date + 7, 'pendente', true, false, true
where not exists (select 1 from public.campanhas);


-- ---------------------------------------------------------
-- 8. TRANSCRIÇÕES (aba nova do painel)
-- Vídeos do YouTube, Instagram ou TikTok que você gosta, com o texto
-- transcrito e as suas observações. Só você lê e escreve, ninguém de fora.
-- ---------------------------------------------------------
create table if not exists public.transcricoes (
  id           bigint generated by default as identity primary key,
  criado_em    timestamptz not null default now(),
  link         text not null default '',
  plataforma   text not null default '',   -- Instagram, YouTube, TikTok ou Outro
  titulo       text not null default '',
  criador      text not null default '',   -- o @ de quem fez o vídeo
  transcricao  text not null default '',   -- o roteiro que você colou
  observacoes  text not null default '',
  exemplo      boolean not null default false
);

alter table public.transcricoes enable row level security;
revoke all on public.transcricoes from anon;
grant select, insert, update, delete on public.transcricoes to authenticated;

drop policy if exists "dona faz tudo" on public.transcricoes;
create policy "dona faz tudo" on public.transcricoes
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

insert into public.transcricoes (titulo, link, plataforma, criador, transcricao, observacoes, exemplo)
select 'Exemplo: reels que eu gostei', '', 'Instagram', '@perfilexemplo',
       'Aqui fica o texto que você copiou do site de transcrição.',
       'Aqui ficam as suas observações: o gancho, o que funcionou, o que dá pra adaptar. Linha de exemplo, pode apagar.',
       true
where not exists (select 1 from public.transcricoes);


-- ---------------------------------------------------------
-- 9. AVISA O SITE QUE AS TABELAS MUDARAM
-- (faz o Supabase enxergar as tabelas novas na hora)
-- ---------------------------------------------------------
notify pgrst, 'reload schema';

-- Pronto! Fim do arquivo.
