-- =========================================================
-- DISPARO DE E-MAILS (aba Prospecção do painel)
--
-- ONDE COLAR:
--   1. Entre em https://supabase.com/dashboard e abra o seu projeto.
--   2. No menu da esquerda, clique em "SQL Editor".
--   3. Clique em "New query" (nova consulta).
--   4. Cole TODO este arquivo e clique em "Run".
--   5. Se aparecer o aviso "Potential issue detected", clique em "Run query":
--      ele aparece por causa do "drop policy if exists", que só troca a
--      regra antiga pela nova. Nada é apagado.
--   6. Tem que aparecer "Success. No rows returned".
--
-- Pode rodar mais de uma vez sem medo.
-- Precisa que o banco.sql já tenha sido rodado antes (ele cria a tabela
-- marcas e a pergunta "quem é a dona", que este arquivo usa).
-- =========================================================


-- ---------------------------------------------------------
-- 1. REGISTRO DE ENVIOS
-- Uma linha por destinatário, em cada disparo. É assim que você sabe
-- quem recebeu e quem não recebeu, mesmo se um disparo parar no meio.
-- ---------------------------------------------------------
create table if not exists public.email_envios (
  id         bigint generated by default as identity primary key,
  data       timestamptz not null default now(),
  email      text not null,
  assunto    text not null default '',
  status     text not null check (status in ('ok', 'erro')),
  erro       text not null default '',      -- o motivo, quando deu errado
  resend_id  text not null default '',      -- o código que o Resend devolve
  canal      text not null default 'resend' check (canal in ('resend', 'gmail')),
  marca_id   bigint                          -- de qual marca era (quando houver)
);
create index if not exists email_envios_email_idx   on public.email_envios (lower(email));
create index if not exists email_envios_assunto_idx on public.email_envios (assunto);
create index if not exists email_envios_data_idx    on public.email_envios (data);


-- ---------------------------------------------------------
-- 2. DESCADASTRO
-- Quem respondeu SAIR. Quem está aqui nunca mais recebe, em nenhum disparo.
-- O e-mail fica sempre em letra minúscula, pra não escapar por diferença
-- de maiúscula.
-- ---------------------------------------------------------
create table if not exists public.email_optout (
  email   text primary key check (email = lower(email)),
  data    timestamptz not null default now(),
  motivo  text not null default ''
);


-- ---------------------------------------------------------
-- 3. DOIS CAMPOS NOVOS NA TABELA DE MARCAS (sem apagar nada)
-- selecionada: a caixinha da aba Marcas, salva pra você marcar hoje e
--              disparar amanhã.
-- enviado_em:  a data em que aquela marca recebeu o seu e-mail.
-- ---------------------------------------------------------
alter table public.marcas add column if not exists selecionada boolean not null default false;
alter table public.marcas add column if not exists enviado_em  date;


-- ---------------------------------------------------------
-- 4. A TRANCA (RLS) NAS DUAS TABELAS NOVAS
-- Só você, logada, lê e escreve. Ninguém deslogado enxerga nada.
-- ---------------------------------------------------------
alter table public.email_envios enable row level security;
alter table public.email_optout enable row level security;

revoke all on public.email_envios, public.email_optout from anon;
grant select, insert, update, delete on public.email_envios, public.email_optout to authenticated;

drop policy if exists "dona faz tudo" on public.email_envios;
create policy "dona faz tudo" on public.email_envios
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));

drop policy if exists "dona faz tudo" on public.email_optout;
create policy "dona faz tudo" on public.email_optout
  for all to authenticated
  using ((select privado.sou_eu())) with check ((select privado.sou_eu()));


-- ---------------------------------------------------------
-- 5. AVISA O SITE QUE AS TABELAS MUDARAM
-- ---------------------------------------------------------
notify pgrst, 'reload schema';

-- Pronto! Fim do arquivo.
